FROM ruby:2.6.6-slim

RUN apt-get update -qq && apt-get -y install \
    build-essential nodejs sqlite3 libsqlite3-dev

WORKDIR /usr/src/myapp

COPY Gemfile* ./

RUN gem install bundler:2.0.0.pre.3 && bundle install

COPY ./ ./

ENTRYPOINT [ "./docker-entrypoint.sh" ]

CMD ["/bin/bash", "-c", "bash"]